### ISSUE TITLE
Supported terminals?

### ISSUE THREAD

**Issue by RyanGlScott** [chhackett/vty-windows#11]
Is there a list of terminals that `vty-windows` is intended to support? I ask since I recently tried running an application (`matterhorn`) that uses mouse support, and while it does work in PowerShell and `cmd.exe`, it _doesn't_ work `mintty`, in the terminal that MSYS2 uses. That being said, it's not clear to me after reading the [`README`](https://github.com/chhackett/vty-windows/blob/655085eb141f2b10601017cb29c0069b190d8288/README.md) if `mintty` is intended to be supported at all. If it isn't, could you add this to a list of "known limitations" somewhere?

**Comment by chhackett** [comment]
I added a note to the README that currently only Powershell and Command Prompt are supported, with one minor issue with colors in Powershell. 

I'll start testing on mintty this week, and see what I can do...

**Comment by RyanGlScott** [comment]
Thanks! That note is exactly what I'm looking for.
