### ISSUE TITLE
add to stackage

### ISSUE THREAD

**Issue by simonmichael** [chhackett/vty-windows#16]
Thanks for vty-windows! Could it be added to stackage nightly, like the other vty-* packages.

**Comment by chhackett** [comment]
@simonmichael 
Oh, yes I can do that I think. I will try to get to it this weekend.
 
Sorry for the inconvenience, I've just never used stack before.

**Comment by simonmichael** [comment]
Thank you! You can just send a PR adding it to https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml .

**Comment by simonmichael** [comment]
(Having it in stackage helps it get packaged more widely and helps with reproducible installs of vty/brick-based apps.)

**Comment by chhackett** [comment]
@simonmichael 
Hello,
So I opened a PR where I added vty-windows to the same list as vty, etc. Unfortunately the check.sh script failed in CI.
So I'm not sure exactly what the process is for adding a package that can only be built on Windows. Should I just add it to the 'skipped-builds' section? Seems like the documentation could be a bit clearer for that scenario.

skipped-builds:
    - hfsevents
    - lzma-clib
    - Win32
    - Win32-notify
    - windns

**Comment by simonmichael** [comment]
I'm not either. I think Stackage only tests builds on GNI/linux. I would just try a PR and see if it passes. Or, #haskell-stack:matrix.org chat room will know.

**Comment by simonmichael** [comment]
Oh, I see the https://github.com/commercialhaskell/stackage/pull/7329 , currently blocked awaiting maintainer approval.

**Comment by simonmichael** [comment]
https://github.com/commercialhaskell/stackage/pull/7385 was also needed. vty-windows is now in stackage (nightly-2024-04-20).
