### ISSUE TITLE
Color handling

### ISSUE THREAD

**Issue by ShrykeWindgrace** [chhackett/vty-windows#5]
Just a quick question on this line ( and its siblings above):
https://github.com/chhackett/vty-windows/blob/main/src/Graphics/Vty/Platform/Windows/Output/Color.hs#L31

IIRC, Windows Terminal support `FullColor`, is there a reason to stick to `Color240`?

**Comment by chhackett** [comment]
Oh, you know I never tested it. I'll switch it over. Btw, another thing I've been starting to think about is whether there is any reason to check for the TERM type anywhere in the Windows plugin code. For example, should we explicitly fail to start in some shells? I know there was odd behavior in, I believe, cygwin right? 

But I haven't tested in different shells in a while. That's something we should look into more carefully I think.

**Comment by ShrykeWindgrace** [comment]
Some conhost-based emulators set the TERM (e.g. `alacritty` sets it to `xterm`); some cygwin-based emulators also set it - you guessed it, also to `xterm`. So, if we use only that environment variable, we can not be sure of the backend.

Then again, there is `WT_SESSION` variable set by WindowsTerminal - that's a better guarantee that we are running under modern conhost. But - there is always a **but** - if we spawn a new console app from WindowsTerminal in a new window, it can be backed by an older conhost, yet it would inherit `WT_SESSION`.
  
So, from my understanding, if we detect a `CYGWIN` variable, we will most probably fail; if we detect `WT_SESSION` we will probably run smoothly. Everything else is a gray area subject to testing with specific emulator and its config.
